version: '3.8'

services:
  books-api:
    build: ./
    command: ./booksApi
    ports:
      - "8880:8880"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
  db:
    restart: always
    image: postgres:latest
    volumes:
      - books_api_db:/var/lib/mysql
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5436:5432"

volumes:
    books_api_db: