// Test generated by RoostGPT for test books-go-test using AI Type Vertex AI and AI Model code-bison

package repository

import (
	"booksApi"
	"github.com/jmoiron/sqlx"
	"testing"
)

func TestUpdate_3fd8b9c5ec(t *testing.T) {
	// Setup
	db, err := sqlx.Open("postgres", "postgres://localhost:5432/books_test")
	if err != nil {
		t.Fatal(err)
	}
	r := &BooksPostgres{db: db}
	input := booksApi.UpdateBookInput{
		Title:  "The Great Gatsby",
		Author: "F. Scott Fitzgerald",
		Year:   1925,
	}

	// Test
	err = r.Update(1, input)

	// Assert
	if err != nil {
		t.Errorf("Update() failed: %v", err)
	}
	t.Log("Update() succeeded")

	// Teardown
	db.Close()
}

func TestUpdate_Error(t *testing.T) {
	// Setup
	db, err := sqlx.Open("postgres", "postgres://localhost:5432/books_test")
	if err != nil {
		t.Fatal(err)
	}
	r := &BooksPostgres{db: db}
	input := booksApi.UpdateBookInput{
		Title:  "The Great Gatsby",
		Author: "F. Scott Fitzgerald",
		Year:   1925,
	}

	// Test
	err = r.Update(-1, input) // ID is negative, which should cause an error

	// Assert
	if err == nil {
		t.Errorf("Update() did not return an error")
	}
	t.Log("Update() failed as expected")

	// Teardown
	db.Close()
}
